### ISSUE TITLE
Allow long URLs in commit messages

### ISSUE THREAD

**Issue by johnboyes** [mristin/opinionated-commit-message#59]
I propose that URLs should always be allowed in the body of commit messages, even when longer than 72 characters.

Given that commit messages should be well-documented, relevant URLs should be encouraged, I'd say.   Alternatives such as using a URL shortener have downsides (makes the writing of the commit message more cumbersome, and makes the actual destination URL opaque).

There seems to be something of a consensus in the open source world around allowing long URLs ([1][1], [2][2], [3][3], [4][4]).

If you agree and decide to add this feature, I'd propose as a potential implementation skipping the line length check for any line that has a URL in it.  I think a check that only allows long URLs if they are the only content on a given line would be too restrictive, as a common approach is to have the urls sequentially numbered as [reference links][5] at the foot of the commit message.

[1]:  https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53#gistcomment-2355038
[2]: https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/21527#note_99156659
[3]: https://github.com/microsoft/vscode/issues/2718#issuecomment-289389110
[4]: https://dragonfly2.readthedocs.io/en/latest/commit_messages.html#example
[5]: https://www.markdownguide.org/basic-syntax/#reference-style-links

**Comment by mristin** [comment]
Thanks for the suggestion! Let me also check what markdown proposes.

Give me a couple of days as it's a busy summer time at the moment.

**Comment by johnboyes** [comment]
Thanks, @mristin, no rush at all :-)

Here's another couple of links regarding markdown and this topic, FYI:

- http://www.rubycoloredglasses.com/2017/11/markdown-links-80-character-line-length/
- https://github.com/markdownlint/markdownlint/issues/128
- https://stackoverflow.com/a/27071588

**Comment by johnboyes** [comment]
Have been thinking about this a little more.  Given that this GitHub Action is opinionated (which is a great thing), one option would be to allow (and encourage) [reference links][1], but not [inline links](https://www.markdownguide.org/basic-syntax/#links)

Personally I think that could be a very nice approach, as reference links are much more elegant than inline links when reading commit messages IMHO, and it would enforce one clear consistent way of specifying links.

Just sharing my thoughts :-)

[1]: https://www.markdownguide.org/basic-syntax/#reference-style-links

**Comment by mristin** [comment]
Hi @johnboyes ,
I finally implemented both versions. I released it as patch version (2.1.1, https://github.com/mristin/opinionated-commit-message/releases/tag/v2.1.1).

Thanks again for the suggestion!

**Comment by johnboyes** [comment]
Thanks v much for implementing this so quickly, @mristin 😎 

I've just given it a quick test and [I'm still getting the long line error][1] after upgrading to `v2.1.1` - v grateful if you can take a look pls?

[1]: https://github.com/agilepathway/hoverfly-github-action/runs/985563534

**Comment by mristin** [comment]
Hi @johnboyes ,
This is a strange bug -- I explicitly test for that case. I'll try to have a look at it during the next week.

**Comment by mristin** [comment]
Hi @johnboyes ,
It seems I simply forgot to include `dist` folder in the commit. Could you please check if the new patch version (2.1.2) works for you?

**Comment by johnboyes** [comment]
Just tested again and works perfectly now, thanks @mristin 👍
